source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

pod 'XLForm'
pod 'ScalePicker'

target 'ScalePickerDemo' do
  inherit! :search_paths
  # Pods for testing
  pod 'XLForm'
  pod 'ScalePicker'
end